before_install:
- sudo apt-get install python
- sudo apt-get install python-dev
- sudo apt-get install python-numpy
- sudo apt-get install make
- sudo apt-get install software-properties-common
- sudo add-apt-repository ppa:george-edison55/cmake-3.x
- 

- sudo apt-get update
- sudo apt-get upgrade

script:
- mkdir bin
- cd bin/
- cmake ../
- make

language:
- c++
