before_install:
- sudo apt-get install python
- sudo apt-get install python-dev
- sudo apt-get install python-numpy
- sudo apt-get install make
- yes "Y" | sudo apt-get upgrade

script:
- mkdir bin
- cd bin/
- cmake ../
- make

language:
- c++
